-------------------------------- REZERVACIJA --------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".REZERVACIJA;
CREATE TABLE "TESTNI_SALON".REZERVACIJA (
	"ID" 		SERIAL 			PRIMARY KEY,
	EMAIL		VARCHAR(50),
	TEL			VARCHAR(20),
	DATUM 		DATE,
	ID_TERMIN	INTEGER,
	UNIQUE		(DATUM, ID_TERMIN)
);


-------------------------------- TERMIN -------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".TERMIN;
CREATE TABLE "TESTNI_SALON".TERMIN (
	"ID" 				INT PRIMARY KEY,
	VRIJEME_POCETAK		TIME,
	VRIJEME_KRAJ		TIME
);

INSERT INTO "TESTNI_SALON".TERMIN VALUES
(1, '09:00:00', '10:00:00'),
(2, '10:00:00', '11:00:00'),
(3, '11:00:00', '12:00:00'),
(4, '13:00:00', '14:00:00'),
(5, '14:00:00', '15:00:00'),
(6, '15:00:00', '16:00:00'),
(7, '16:00:00', '17:00:00');


-------------------------------- DATUM --------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".DATUM;
CREATE TABLE "TESTNI_SALON".DATUM (
	"ID" 			SERIAL PRIMARY KEY,
	DAN				DATE UNIQUE,
	RADNI_DAN		BOOLEAN
);

CREATE OR REPLACE FUNCTION "TESTNI_SALON".INSERT_DATES(
	start_date 	DATE,
	end_date 	DATE) RETURNS VOID AS $$
DECLARE
    current DATE := start_date;
    is_workday BOOLEAN;
BEGIN
    WHILE current <= end_date LOOP
        IF EXTRACT(ISODOW FROM current) IN (6, 7) THEN
            is_workday := FALSE;
        ELSE
            is_workday := TRUE;
        END IF;

        INSERT INTO "TESTNI_SALON".DATUM (DAN, RADNI_DAN) VALUES (current, is_workday);
        
        current := current + 1;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

SELECT "TESTNI_SALON".INSERT_DATES('2024-03-01', '2024-05-31');


-------------------------------- KORISNIK --------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".KORISNIK;
CREATE TABLE "TESTNI_SALON".KORISNIK (
	"ID" 		SERIAL	 		PRIMARY KEY,
	EMAIL		VARCHAR(50) 	UNIQUE NOT NULL,
	LOZINKA		VARCHAR 	 	NOT NULL,
	IME			VARCHAR(50)		NOT NULL,	
	PREZIME		VARCHAR(50)		NOT NULL,
	ULOGA		SMALLINT		NOT NULL
);


-------------------------------- ULOGA --------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".ULOGA;
CREATE TABLE "TESTNI_SALON".ULOGA (
	"ID" 		INTEGER 		PRIMARY KEY,
	IME_ULOGE	VARCHAR(10)		NOT NULL
);

INSERT INTO "TESTNI_SALON".ULOGA VALUES 
(0, 'korisnik'),
(1, 'admin');


-------------------------------- PROIZVOD --------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".PROIZVOD;
CREATE TABLE "TESTNI_SALON".PROIZVOD (
	"ID" 			SERIAL	 		PRIMARY KEY,
	ID_KATEGORIJA	INTEGER			NOT NULL,
	IME				VARCHAR(50) 	NOT NULL,
	OPIS			VARCHAR 	 	NOT NULL,
	CIJENA			NUMERIC(10,2)	NOT NULL
);


-------------------------------- KATEGORIJA --------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".KATEGORIJA;
CREATE TABLE "TESTNI_SALON".KATEGORIJA (
	"ID" 			INTEGER 		PRIMARY KEY,
	IME_KATEGORIJE	VARCHAR(50)		NOT NULL
);

INSERT INTO "TESTNI_SALON".KATEGORIJA VALUES 
(0, 'Njega'),
(1, 'Styling'),
(2, 'Oprema');


-------------------------------- OMILJENI_PROIZVOD --------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".OMILJENI_PROIZVOD;
CREATE TABLE "TESTNI_SALON".OMILJENI_PROIZVOD (
	ID_KORISNIK 	INTEGER,
	ID_PROIZVOD 	INTEGER,
	PRIMARY KEY (ID_KORISNIK, ID_PROIZVOD)
);


-------------------------------- DOBAVLJAC --------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".DOBAVLJAC;
CREATE TABLE "TESTNI_SALON".DOBAVLJAC (
	"ID" 	SERIAL PRIMARY KEY,
	EMAIL   VARCHAR(100),
	IME 	VARCHAR(500)
);


-------------------------------- PROIZVOD_DOBAVLJAC --------------------------------------
DROP TABLE IF EXISTS "TESTNI_SALON".PROIZVOD_DOBAVLJAC;
CREATE TABLE "TESTNI_SALON".PROIZVOD_DOBAVLJAC (
	ID_PROIZVOD 		INTEGER,
	ID_DOBAVLJAC 		INTEGER,
	NABAVNA_CIJENA		NUMERIC(10,2),
	PRSJ_DANA_ISPORUKE	INTEGER,
	PRIMARY KEY (ID_PROIZVOD, ID_DOBAVLJAC)
);


-------------------------------- CONSTRAINTS --------------------------------------
ALTER TABLE "TESTNI_SALON".REZERVACIJA ADD CONSTRAINT fk_REZERVACIJA_KORISNIK
FOREIGN KEY (EMAIL) REFERENCES "TESTNI_SALON".KORISNIK(EMAIL);

ALTER TABLE "TESTNI_SALON".REZERVACIJA ADD CONSTRAINT fk_REZERVACIJA_TERMIN
FOREIGN KEY (ID_TERMIN) REFERENCES "TESTNI_SALON".TERMIN("ID");

ALTER TABLE "TESTNI_SALON".REZERVACIJA ADD CONSTRAINT fk_REZERVACIJA_DATUM
FOREIGN KEY (DATUM) REFERENCES "TESTNI_SALON".DATUM(DAN);

ALTER TABLE "TESTNI_SALON".KORISNIK ADD CONSTRAINT fk_KORISNIK_ULOGA
FOREIGN KEY (ULOGA) REFERENCES "TESTNI_SALON".ULOGA("ID");

ALTER TABLE "TESTNI_SALON".PROIZVOD ADD CONSTRAINT fk_PROIZVOD_KATEGORIJA
FOREIGN KEY (ID_KATEGORIJA) REFERENCES "TESTNI_SALON".KATEGORIJA("ID");

ALTER TABLE "TESTNI_SALON".OMILJENI_PROIZVOD ADD CONSTRAINT fk_OMILJENI_PROIZVOD_KORISNIK
FOREIGN KEY (ID_KORISNIK) REFERENCES "TESTNI_SALON".KORISNIK("ID");

ALTER TABLE "TESTNI_SALON".OMILJENI_PROIZVOD ADD CONSTRAINT fk_OMILJENI_PROIZVOD_PROIZVOD
FOREIGN KEY (ID_PROIZVOD) REFERENCES "TESTNI_SALON".PROIZVOD("ID");


------------------------------------------------------------------------------------

SELECT * FROM "TESTNI_SALON".PROIZVOD;

TRUNCATE TABLE "TESTNI_SALON".proizvod;
INSERT INTO "TESTNI_SALON".PROIZVOD VALUES
(default, 0, 'Krema za kosu', 'Luda i nezaboravna krema za kosu', 9.1),
(default, 0, 'Šampon za kosu', 'Ludi i nezaboravni šampon za kosu', 5.3),
(default, 1, 'Gel', 'Da kosa stoji u zraku', 12),
(default, 2, 'Škare', 'cvik cvik', 11.1),
(default, 2, 'Mašinica', 'zzzzzzz', 9.9),
(default, 2, 'Fen', 'ZZZZZZZZZZ', 129.13),
(default, 2, 'Britvica', 'ksssss', 1.1)


SELECT * FROM "TESTNI_SALON".dobavljac;

TRUNCATE TABLE "TESTNI_SALON".dobavljac
INSERT INTO "TESTNI_SALON".dobavljac VALUES
(default, 'misko.miskic@gmail.com', 'Misko'),
(default, 'joza.jozic@hotmail.com', 'Joza'),
(default, 'stef.stefanovic@gmail.com', 'Stef');


select * from "TESTNI_SALON".proizvod_dobavljac;

TRUNCATE TABLE "TESTNI_SALON".proizvod_dobavljac
INSERT INTO "TESTNI_SALON".proizvod_dobavljac VALUES
(39, 14, 2, 10),
(39, 15, 2.5, 9);



